services:
  nginx:
    image: nginx:alpine
    container_name: projet-devops-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:rw
    networks:
      - app-network
    depends_on:
      app-blue:
        condition: service_started
        required: false
      app-green:
        condition: service_started
        required: false

  app-blue:
    image: projet-devops:multistage
    container_name: projet-devops-app-blue
    profiles:
      - blue
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_COLOR: blue
      DEPLOY_SHA: ${DEPLOY_SHA:-unknown}
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  app-green:
    image: projet-devops:multistage
    container_name: projet-devops-app-green
    profiles:
      - green
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_COLOR: green
      DEPLOY_SHA: ${DEPLOY_SHA:-unknown}
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: projet-devops-redis
    networks:
      - app-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app-network:

volumes:
  redis-data:
